# Generated by Django 5.1.15 on 2026-01-15 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voter', '0005_remove_voter_password_voter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blinded_hash', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voter.voter')),
            ],
        ),
    ]
