# Generated by Django 5.1.15 on 2026-03-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_electionstate_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
