# Generated by Django 6.0 on 2026-01-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='voter',
            new_name='student',
        ),
    ]
