# Generated by Django 6.0 on 2026-01-05 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_voter_is_voted_voter_password_alter_voter_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
